/// @description Check Save

#macro HRTPSAVE "HRtPSave.dat"
#macro SOEWSAVE "SoEWSave.dat"
#macro PODDSAVE "PoDDSave.dat"
#macro LLSSAVE "LLSSave.dat"
#macro MSSAVE "MSSave.dat"
#macro EOSDSAVE "EoSDSave.dat"
#macro PCBSAVE "PCBSave.dat"
#macro IAMPSAVE "IAMPSave.dat"
#macro INSAVE "INSave.dat"
#macro POFVSAVE "POFVSave.dat"
#macro STBSAVE "STBSave.dat"
#macro MOFSAVE "MOFSave.dat"
#macro SWRSAVE "SWRSave.dat"
#macro SASAVE "SASave.dat"
#macro UFOSAVE "UFOSave.dat"
#macro HISOUSAVE "HISOUSave.dat"
#macro DSSAVE "DSSave.dat"
#macro GFWSAVE "GFWSave.dat"
#macro TDSAVE "TDSave.dat"
#macro HMSAVE "HMSave.dat"
#macro DDCSAVE "DDCSave.dat"
#macro ISCSAVE "ISCSave.dat"
#macro ULILSAVE "ULILSave.dat"
#macro LOLKSAVE "LOLKSave.dat"
#macro AOCFSAVE "AOCFSave.dat"
#macro HSIFSSAVE "HSIFSSave.dat"
#macro VDSAVE "VDSave.dat"
#macro WBAWCSAVE "WBAWCSave.dat"
#macro SFWSAVE "SFWSave.dat"
#macro UMSAVE "UMSave.dat"
#macro OBMSAVE "100BMSave.dat"
#macro UDOALGSAVE "UDOALGSave.dat"
#macro FWSAVE "FWSave.dat"


SaveCheck();